version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER : "ebilling"
      POSTGRES_PASSWORD : "Abcd@1234"
      POSTGRES_DB : "ebilling"
    volumes:
      - db5432:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db5432:
